/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.awt.Color;
import javax.swing.colorchooser.DefaultColorSelectionModel;

/**
 *
 * @author ADMIN
 */
public class San_Pham extends javax.swing.JInternalFrame {

    
    Color DefaultColor,ClickedColor;
    
    
    public San_Pham() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        DefaultColor=new Color(153,51,0);
        ClickedColor=new Color(204,0,51);
        
        Coffee.setOpaque(true);
        juices.setOpaque(true);
        Milk_tea.setOpaque(true);
        
        Coffee.setBackground(DefaultColor);
        juices.setBackground(DefaultColor);
        Milk_tea.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Milk_tea = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Coffee = new javax.swing.JLabel();
        juices = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(732, 617));

        jPanel1.setBackground(new java.awt.Color(153, 51, 0));

        Milk_tea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tea_milk.png"))); // NOI18N
        Milk_tea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Milk_teaMousePressed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/954591.png"))); // NOI18N

        Coffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffee.png"))); // NOI18N
        Coffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CoffeeMousePressed(evt);
            }
        });

        juices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/juices.png"))); // NOI18N
        juices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                juicesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Coffee)
                .addGap(30, 30, 30)
                .addComponent(juices)
                .addGap(32, 32, 32)
                .addComponent(Milk_tea)
                .addGap(102, 102, 102)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(juices)
                    .addComponent(Coffee)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Milk_tea))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(475, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CoffeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoffeeMousePressed
        Coffee.setBackground(ClickedColor);
        juices.setBackground(DefaultColor);
        Milk_tea.setBackground(DefaultColor);
    }//GEN-LAST:event_CoffeeMousePressed

    private void juicesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juicesMousePressed
        Coffee.setBackground(DefaultColor);
        juices.setBackground(ClickedColor);
        Milk_tea.setBackground(DefaultColor);
    }//GEN-LAST:event_juicesMousePressed

    private void Milk_teaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Milk_teaMousePressed
       Coffee.setBackground(DefaultColor);
        juices.setBackground(DefaultColor);
        Milk_tea.setBackground(ClickedColor);
    }//GEN-LAST:event_Milk_teaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Coffee;
    private javax.swing.JLabel Milk_tea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel juices;
    // End of variables declaration//GEN-END:variables
}
